spring:
  cloud:
    stream:
      bindings:
        input-channel-1:
          destination: my-topic
      kafka:
        streams:
          binder:
            application-id: basic-stream-listener
            brokers: localhost:9092
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
